version: '3.8'

services:
  backend:
    image: bobohsn/amazona-backend:latest
    container_name: amazona-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/amazona
    restart: always

  frontend:
    image: bobohsn/amazona-frontend:latest
    container_name: amazona-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
